FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api.py .
COPY ingest.py .
COPY data.txt .
# 复制本地已经生成好的 chroma_db
COPY chroma_db ./chroma_db

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]